In [4]:
import numpy as np
import cv2

In [5]:
a = np.array([[1,2,3],[2,3,4],[3,4,5]])

In [10]:
a[1:2,0:2]

array([[2, 3]])

In [7]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [31]:
a = np.random.rand(8,8)

In [32]:
a

array([[0.35618467, 0.02837903, 0.39797087, 0.92006727, 0.98917634,
        0.63192461, 0.8472695 , 0.81888776],
       [0.70017685, 0.44392463, 0.70144464, 0.88604855, 0.71700485,
        0.07751916, 0.37483175, 0.89986348],
       [0.97046984, 0.8443659 , 0.2408525 , 0.75269816, 0.9251619 ,
        0.17311686, 0.75314951, 0.83462034],
       [0.72926497, 0.71915544, 0.69076851, 0.40279327, 0.35966588,
        0.28879797, 0.72751692, 0.75086864],
       [0.69908633, 0.76435859, 0.61184175, 0.21064931, 0.93614843,
        0.09801753, 0.03970678, 0.50322535],
       [0.97950527, 0.92605233, 0.0779439 , 0.50450832, 0.93607556,
        0.22723218, 0.41859856, 0.39333238],
       [0.73909531, 0.3787283 , 0.56775781, 0.95571785, 0.61341216,
        0.60577994, 0.20076225, 0.79489182],
       [0.05009809, 0.28410517, 0.21270179, 0.06611679, 0.76883949,
        0.97068457, 0.22673689, 0.30558425]])

In [37]:
shape = (4,4,2,2)
stride = np.array([8, 2, 8, 1]) * a.itemsize
img_c = np.lib.stride_tricks.as_strided(a, shape, stride)
img_c.shape

(4, 4, 2, 2)

In [42]:
count = 0
for x in img_c:
    for y in x:
        count+=1
count

16

In [45]:
a = 1;b = 2
np.hypot(a,b)

2.23606797749979

In [46]:
5**0.5

2.23606797749979

In [49]:
a = 3
np.rad2deg(-4.14)

-237.2045271841608

In [55]:
g = np.array([1,2,3,4,5])
a = np.array([-3, -1, 1, 1, 3])
histogram = np.histogram(a,bins=8, range=(-np.pi,np.pi), weights=g)

In [56]:
histogram

(array([1, 0, 2, 0, 0, 7, 0, 5]),
 array([-3.14159265, -2.35619449, -1.57079633, -0.78539816,  0.        ,
         0.78539816,  1.57079633,  2.35619449,  3.14159265]))

In [57]:
np.empty((3))

array([2.5e-323, 3.0e-323, 3.5e-323])

In [109]:
a = np.array([[]])
b = np.arange(4)

In [112]:
b[0:]

array([0, 1, 2, 3])

In [102]:
c.reshape((4,))

ValueError: cannot reshape array of size 8 into shape (4,)

In [103]:
c

array([[1., 2., 3., 4.],
       [1., 1., 1., 1.]])